test rsync 03

diff --git a/.github/workflows/build-wine-tkg.yml b/.github/workflows/build-wine-tkg.yml
--- a/.github/workflows/build-wine-tkg.yml
+++ b/.github/workflows/build-wine-tkg.yml
@@ -50,44 +50,50 @@ jobs:
           exit 0' > md5.sh
           bash md5.sh
           
-      - name: Publish Package on GitHub
-        shell: bash
-        run: |
-          release=$(find . -name *.zst | cut -d "/" -f2)
-          echo ${{ github.token }} | gh auth login --with-token
-          cd wine-tkg-git/wine-tkg-git
-          ls -lh
-          gh release create ${release} --title ${release} --repo ${{ github.repository }} --notes "automated release from ${{ github.event.client_payload.url }}" || echo "release already exists"
-          GITHUB_LINK=https://github.com/${GITHUB_REPOSITORY}/releases/download/${release}
-          for i in .zst .sig .tar .md5; do
-          find -iname "*$i" -exec gh release upload ${release} --repo ${GITHUB_REPOSITORY} --clobber {} \;
-          done
+  push:
+    runs-on: ubuntu-latest
+      # Tmate ##
+      - name: Setup TMATE Session
+        uses: mxschmitt/action-tmate@v3
           
-      - name: Push to Repo
-        shell: bash
-        run: |
-          echo "## ssh setup"
-          mkdir -p /home/runner/.ssh
-          touch /home/runner/.ssh/id_rsa
-          chmod 600 /home/runner/.ssh/id_rsa
-          #ssh-agent -a /tmp/ssh_agent.sock > /dev/null
-          echo "${{ secrets.PKGBUILD_KEY }}" >> /home/runner/.ssh/id_rsa
-          eval `ssh-agent -s`
-          #ssh-add /home/runner/.ssh/github_actions
-          ssh-keyscan -t rsa -p ${{ secrets.PKGBUILD_PORT }} ${{ secrets.PKGBUILD_HOST }} >> /home/runner/.ssh/known_hosts
-          
-          cd wine-tkg-git/wine-tkg-git
-          ls -lh
-          if [ -n "$(echo ${{ github.event.client_payload.branch }} | grep stable )" ];then branch=stable; else branch=testing; fi
-          #for i in *.zst *.sig *.md5; do
-          #test -e $i && rsync -vapz -e "ssh -p ${{ secrets.PKGBUILD_PORT }}" $i ${{ secrets.PKGBUILD_USER }}@${{ secrets.PKGBUILD_HOST }}:${{ secrets.PKGBUILD_DIR }}/$branch
-          #sleep 10
+      #- name: Publish Package on GitHub
+        #shell: bash
+        #run: |
+          #release=$(find . -name *.zst | cut -d "/" -f2)
+          #echo ${{ github.token }} | gh auth login --with-token
+          #cd wine-tkg-git/wine-tkg-git
+          #ls -lh
+          #gh release create ${release} --title ${release} --repo ${{ github.repository }} --notes "automated release from ${{ github.event.client_payload.url }}" || echo "release already exists"
+          #GITHUB_LINK=https://github.com/${GITHUB_REPOSITORY}/releases/download/${release}
+          #for i in .zst .sig .tar .md5; do
+          #find -iname "*$i" -exec gh release upload ${release} --repo ${GITHUB_REPOSITORY} --clobber {} \;
           #done
-          #exit 0
           
-          rsync -vapz -e "ssh -p ${{ secrets.PKGBUILD_PORT }}" PKGBUILD ${{ secrets.PKGBUILD_USER }}@${{ secrets.PKGBUILD_HOST }}:${{ secrets.PKGBUILD_DIR }}/$branch
+      #- name: Push to Repo
+        #shell: bash
+        #run: |
+          #echo "## ssh setup"
+          #mkdir -p /home/runner/.ssh
+          #touch /home/runner/.ssh/id_rsa
+          #chmod 600 /home/runner/.ssh/id_rsa
+          ##ssh-agent -a /tmp/ssh_agent.sock > /dev/null
+          #echo "${{ secrets.PKGBUILD_KEY }}" >> /home/runner/.ssh/id_rsa
+          #eval `ssh-agent -s`
+          ##ssh-add /home/runner/.ssh/github_actions
+          #ssh-keyscan -t rsa -p ${{ secrets.PKGBUILD_PORT }} ${{ secrets.PKGBUILD_HOST }} >> /home/runner/.ssh/known_hosts
           
-      - name: Telegram Alert Fail
-        if: ${{ failure() || cancelled() }}
-        run: |
-          curl -X POST -H 'Content-Type: application/json' -d '{"chat_id": "${{ secrets.CHAT_ID }}", "text": "FALHA ao criar Pacote: ${{ github.event.action }} a partir do branch ${{ github.ref_name }}, link do erro: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}", "disable_notification": false}' ${{ secrets.MESSAGE_BOT_KEY }}
+          #cd wine-tkg-git/wine-tkg-git
+          #ls -lh
+          #if [ -n "$(echo ${{ github.event.client_payload.branch }} | grep stable )" ];then branch=stable; else branch=testing; fi
+          ##for i in *.zst *.sig *.md5; do
+          ##test -e $i && rsync -vapz -e "ssh -p ${{ secrets.PKGBUILD_PORT }}" $i ${{ secrets.PKGBUILD_USER }}@${{ secrets.PKGBUILD_HOST }}:${{ secrets.PKGBUILD_DIR }}/$branch
+          ##sleep 10
+          ##done
+          ##exit 0
+          
+          #rsync -vapz -e "ssh -p ${{ secrets.PKGBUILD_PORT }}" PKGBUILD ${{ secrets.PKGBUILD_USER }}@${{ secrets.PKGBUILD_HOST }}:${{ secrets.PKGBUILD_DIR }}/$branch
+          
+      #- name: Telegram Alert Fail
+        #if: ${{ failure() || cancelled() }}
+        #run: |
+          #curl -X POST -H 'Content-Type: application/json' -d '{"chat_id": "${{ secrets.CHAT_ID }}", "text": "FALHA ao criar Pacote: ${{ github.event.action }} a partir do branch ${{ github.ref_name }}, link do erro: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}", "disable_notification": false}' ${{ secrets.MESSAGE_BOT_KEY }}
